
/* === DEPLOY-SAFE LANGUAGE FIX: make selected language actually apply everywhere === */
(function(){
  const RTL = new Set(['ar','he','ur','fa','ps','ku','sd','ug','yi']);
  const PACKS = {
    en:{native:'English',dir:'ltr',language:'Language',languageHelp:'Choose the language for the app interface.',menu:'Menu',dashboard:'Dashboard',patients:'Patients',addPatient:'Add Patient',scanQR:'Scan QR',settings:'Settings',profile:'Profile',manageUsers:'Manage Users',logout:'Logout',search:'Search by name, phone, ID, or diagnosis...',totalPatients:'Total Patients',todaysAppts:"Today's Appts",unpaidBalance:'Unpaid Balance',totalVisits:'Total Visits',totalRevenue:'Total Revenue',paidToday:'Paid Today',clinicOverview:'Clinic Overview',appointmentCalendar:'Appointment Calendar',today:'Today',upcoming:'Upcoming',newPatient:'+ New Patient',backup:'Backup',restore:'Restore',open:'Open',withoutTreatmentPlan:'without treatment plan',overdue:'overdue',unpaid:'unpaid',followUpWatch:'Follow-up Watch',treatmentStats:'Treatment Stats',unpaidPriority:'Unpaid Priority',remaining:'Remaining',cases:'cases',photos:'Photos / X-rays',clinical:'Clinical',xray:'X-ray',beforeAfter:'Before / After',general:'General',before:'Before',after:'After',photoOptions:'Photo options',markAs:'Mark as',viewPhoto:'View photo',theme:'Theme color',themeHelp:'Choose a premium preset or pick any custom color.',customColor:'Custom color',applyCustom:'Apply custom color',presets:'Premium presets',pdf:'PDF style',doctorCard:'Doctor card',signature:'Draw signature',tools:'Clinic tools and preferences in one simple place.',noBA:'Mark one photo as Before and one photo as After from the 3-dot menu.',noPhotos:'No photos in this section yet.',baHint:'The Before and After photos are selected from the 3-dot menu. Move the bar for a soft blurry transition.',addPayment:'+ Add Payment',installments:'Installments',receipt:'Receipt',delete:'Delete',patientTimeline:'Patient Timeline',visit:'Visit'},
    ar:{native:'العربية',dir:'rtl',language:'اللغة',languageHelp:'اختر لغة واجهة التطبيق.',menu:'القائمة',dashboard:'لوحة التحكم',patients:'المرضى',addPatient:'إضافة مريض',scanQR:'مسح QR',settings:'الإعدادات',profile:'الملف الشخصي',manageUsers:'إدارة المستخدمين',logout:'تسجيل الخروج',search:'ابحث بالاسم أو الهاتف أو الكود أو التشخيص...',totalPatients:'إجمالي المرضى',todaysAppts:'مواعيد اليوم',unpaidBalance:'المتبقي غير المدفوع',totalVisits:'إجمالي الزيارات',totalRevenue:'إجمالي الإيرادات',paidToday:'مدفوع اليوم',clinicOverview:'نظرة عامة على العيادة',appointmentCalendar:'تقويم المواعيد',today:'اليوم',upcoming:'القادم',newPatient:'+ مريض جديد',backup:'نسخة احتياطية',restore:'استرجاع',open:'فتح',withoutTreatmentPlan:'بدون خطة علاج',overdue:'متأخر',unpaid:'غير مدفوع',followUpWatch:'متابعة المرضى',treatmentStats:'إحصائيات العلاج',unpaidPriority:'أولوية المتبقي',remaining:'المتبقي',cases:'حالات',photos:'الصور / الأشعة',clinical:'سريري',xray:'أشعة',beforeAfter:'قبل / بعد',general:'عام',before:'قبل',after:'بعد',photoOptions:'خيارات الصورة',markAs:'تحديد كـ',viewPhoto:'عرض الصورة',theme:'لون التطبيق',themeHelp:'اختر لوناً جاهزاً أو لوناً مخصصاً.',customColor:'لون مخصص',applyCustom:'تطبيق اللون',presets:'ألوان مميزة',pdf:'شكل PDF',doctorCard:'بطاقة الطبيب',signature:'رسم التوقيع',tools:'أدوات العيادة والإعدادات في مكان واحد.',noBA:'حدد صورة قبل وصورة بعد من قائمة الثلاث نقاط.',noPhotos:'لا توجد صور في هذا القسم.',baHint:'صور قبل وبعد يتم اختيارها من قائمة الثلاث نقاط. حرّك الشريط لانتقال ضبابي ناعم.',addPayment:'+ إضافة دفعة',installments:'الأقساط',receipt:'إيصال',delete:'حذف',patientTimeline:'سجل المريض',visit:'زيارة'},
    fr:{native:'Français',dir:'ltr',language:'Langue',languageHelp:'Choisissez la langue de l’interface.',menu:'Menu',dashboard:'Tableau',patients:'Patients',addPatient:'Ajouter patient',scanQR:'Scanner QR',settings:'Réglages',profile:'Profil',manageUsers:'Utilisateurs',logout:'Déconnexion',search:'Rechercher nom, téléphone, ID ou diagnostic...',totalPatients:'Total patients',todaysAppts:'RDV du jour',unpaidBalance:'Solde impayé',totalVisits:'Total visites',totalRevenue:'Revenu total',paidToday:'Payé aujourd’hui',clinicOverview:'Vue clinique',appointmentCalendar:'Calendrier',today:'Aujourd’hui',upcoming:'À venir',newPatient:'+ Nouveau patient',backup:'Sauvegarde',restore:'Restaurer',open:'Ouvrir',withoutTreatmentPlan:'sans plan de traitement',overdue:'en retard',unpaid:'impayé',followUpWatch:'Suivi',treatmentStats:'Statistiques traitement',unpaidPriority:'Impayés prioritaires',remaining:'Restant',cases:'cas',photos:'Photos / Radios',clinical:'Clinique',xray:'Radio',beforeAfter:'Avant / Après',general:'Général',before:'Avant',after:'Après',photoOptions:'Options photo',markAs:'Marquer comme',viewPhoto:'Voir photo',theme:'Couleur',themeHelp:'Choisissez une couleur premium ou personnalisée.',customColor:'Couleur personnalisée',applyCustom:'Appliquer',presets:'Couleurs premium',pdf:'Style PDF',doctorCard:'Carte médecin',signature:'Signature',tools:'Outils et préférences de la clinique.',noBA:'Marquez une photo Avant et une photo Après depuis le menu à 3 points.',noPhotos:'Aucune photo dans cette section.',baHint:'Les photos Avant/Après viennent du menu à 3 points. Déplacez la barre pour une transition douce.',addPayment:'+ Ajouter paiement',installments:'Versements',receipt:'Reçu',delete:'Supprimer',patientTimeline:'Historique patient',visit:'Visite'},
    es:{native:'Español',dir:'ltr',language:'Idioma',languageHelp:'Elige el idioma de la interfaz.',menu:'Menú',dashboard:'Panel',patients:'Pacientes',addPatient:'Añadir paciente',scanQR:'Escanear QR',settings:'Ajustes',profile:'Perfil',manageUsers:'Usuarios',logout:'Salir',search:'Buscar nombre, teléfono, ID o diagnóstico...',totalPatients:'Pacientes totales',todaysAppts:'Citas de hoy',unpaidBalance:'Saldo pendiente',totalVisits:'Visitas totales',totalRevenue:'Ingresos totales',paidToday:'Pagado hoy',clinicOverview:'Resumen clínica',appointmentCalendar:'Calendario',today:'Hoy',upcoming:'Próximas',newPatient:'+ Nuevo paciente',backup:'Copia',restore:'Restaurar',open:'Abrir',withoutTreatmentPlan:'sin plan de tratamiento',overdue:'atrasado',unpaid:'pendiente',followUpWatch:'Seguimiento',treatmentStats:'Estadísticas',unpaidPriority:'Pendientes prioritarios',remaining:'Restante',cases:'casos',photos:'Fotos / Rayos X',clinical:'Clínica',xray:'Rayos X',beforeAfter:'Antes / Después',general:'General',before:'Antes',after:'Después',photoOptions:'Opciones de foto',markAs:'Marcar como',viewPhoto:'Ver foto',theme:'Color',themeHelp:'Elige un color premium o personalizado.',customColor:'Color personalizado',applyCustom:'Aplicar color',presets:'Colores premium',pdf:'Estilo PDF',doctorCard:'Tarjeta doctor',signature:'Firma',tools:'Herramientas y preferencias de la clínica.',noBA:'Marca una foto como Antes y otra como Después desde el menú de 3 puntos.',noPhotos:'No hay fotos en esta sección.',baHint:'Las fotos Antes/Después se eligen desde el menú de 3 puntos. Mueve la barra para una transición suave.',addPayment:'+ Añadir pago',installments:'Cuotas',receipt:'Recibo',delete:'Eliminar',patientTimeline:'Historial del paciente',visit:'Visita'},
    de:{native:'Deutsch',dir:'ltr',language:'Sprache',languageHelp:'Wählen Sie die Sprache der App.',menu:'Menü',dashboard:'Dashboard',patients:'Patienten',addPatient:'Patient hinzufügen',scanQR:'QR scannen',settings:'Einstellungen',profile:'Profil',manageUsers:'Benutzer',logout:'Abmelden',search:'Name, Telefon, ID oder Diagnose suchen...',totalPatients:'Patienten gesamt',todaysAppts:'Termine heute',unpaidBalance:'Offener Betrag',totalVisits:'Besuche gesamt',totalRevenue:'Umsatz gesamt',paidToday:'Heute bezahlt',clinicOverview:'Praxisübersicht',appointmentCalendar:'Kalender',today:'Heute',upcoming:'Anstehend',newPatient:'+ Neuer Patient',backup:'Backup',restore:'Wiederherstellen',open:'Öffnen',withoutTreatmentPlan:'ohne Behandlungsplan',overdue:'überfällig',unpaid:'unbezahlt',followUpWatch:'Nachverfolgung',treatmentStats:'Behandlungsstatistik',unpaidPriority:'Offene Zahlungen',remaining:'Restbetrag',cases:'Fälle',photos:'Fotos / Röntgen',clinical:'Klinisch',xray:'Röntgen',beforeAfter:'Vorher / Nachher',general:'Allgemein',before:'Vorher',after:'Nachher',photoOptions:'Fotooptionen',markAs:'Markieren als',viewPhoto:'Foto ansehen',theme:'Farbe',themeHelp:'Wählen Sie eine Premium- oder eigene Farbe.',customColor:'Eigene Farbe',applyCustom:'Anwenden',presets:'Premiumfarben',pdf:'PDF-Stil',doctorCard:'Arztkarte',signature:'Unterschrift',tools:'Praxiswerkzeuge und Einstellungen.',noBA:'Markieren Sie ein Foto als Vorher und eines als Nachher im Drei-Punkte-Menü.',noPhotos:'Keine Fotos in diesem Bereich.',baHint:'Vorher/Nachher-Fotos werden im Drei-Punkte-Menü gewählt. Bewegen Sie den Regler für weichen Übergang.',addPayment:'+ Zahlung hinzufügen',installments:'Raten',receipt:'Quittung',delete:'Löschen',patientTimeline:'Patientenverlauf',visit:'Besuch'},
    it:{native:'Italiano',dir:'ltr',language:'Lingua',languageHelp:'Scegli la lingua dell’interfaccia.',menu:'Menu',dashboard:'Cruscotto',patients:'Pazienti',addPatient:'Aggiungi paziente',scanQR:'Scansiona QR',settings:'Impostazioni',profile:'Profilo',manageUsers:'Utenti',logout:'Esci',search:'Cerca nome, telefono, ID o diagnosi...',totalPatients:'Pazienti totali',todaysAppts:'Appuntamenti oggi',unpaidBalance:'Saldo non pagato',totalVisits:'Visite totali',totalRevenue:'Entrate totali',paidToday:'Pagato oggi',clinicOverview:'Panoramica clinica',appointmentCalendar:'Calendario',today:'Oggi',upcoming:'Prossimi',newPatient:'+ Nuovo paziente',backup:'Backup',restore:'Ripristina',open:'Apri',withoutTreatmentPlan:'senza piano di trattamento',overdue:'in ritardo',unpaid:'non pagato',followUpWatch:'Follow-up',treatmentStats:'Statistiche trattamenti',unpaidPriority:'Pagamenti aperti',remaining:'Rimanente',cases:'casi',photos:'Foto / Radiografie',clinical:'Clinica',xray:'Radiografia',beforeAfter:'Prima / Dopo',general:'Generale',before:'Prima',after:'Dopo',photoOptions:'Opzioni foto',markAs:'Segna come',viewPhoto:'Vedi foto',theme:'Colore',themeHelp:'Scegli un colore premium o personalizzato.',customColor:'Colore personalizzato',applyCustom:'Applica',presets:'Colori premium',pdf:'Stile PDF',doctorCard:'Scheda medico',signature:'Firma',tools:'Strumenti e preferenze della clinica.',noBA:'Segna una foto come Prima e una come Dopo dal menu a 3 punti.',noPhotos:'Nessuna foto in questa sezione.',baHint:'Le foto Prima/Dopo vengono scelte dal menu a 3 punti. Muovi la barra per una transizione morbida.',addPayment:'+ Aggiungi pagamento',installments:'Rate',receipt:'Ricevuta',delete:'Elimina',patientTimeline:'Cronologia paziente',visit:'Visita'},
    pt:{native:'Português',dir:'ltr',language:'Idioma',languageHelp:'Escolha o idioma da interface.',menu:'Menu',dashboard:'Painel',patients:'Pacientes',addPatient:'Adicionar paciente',scanQR:'Ler QR',settings:'Configurações',profile:'Perfil',manageUsers:'Usuários',logout:'Sair',search:'Pesquisar nome, telefone, ID ou diagnóstico...',totalPatients:'Total de pacientes',todaysAppts:'Consultas hoje',unpaidBalance:'Saldo em aberto',totalVisits:'Total de visitas',totalRevenue:'Receita total',paidToday:'Pago hoje',clinicOverview:'Visão da clínica',appointmentCalendar:'Calendário',today:'Hoje',upcoming:'Próximas',newPatient:'+ Novo paciente',backup:'Backup',restore:'Restaurar',open:'Abrir',withoutTreatmentPlan:'sem plano de tratamento',overdue:'atrasado',unpaid:'em aberto',followUpWatch:'Acompanhamento',treatmentStats:'Estatísticas',unpaidPriority:'Pendentes prioritários',remaining:'Restante',cases:'casos',photos:'Fotos / Raios X',clinical:'Clínica',xray:'Raio X',beforeAfter:'Antes / Depois',general:'Geral',before:'Antes',after:'Depois',photoOptions:'Opções da foto',markAs:'Marcar como',viewPhoto:'Ver foto',theme:'Cor',themeHelp:'Escolha uma cor premium ou personalizada.',customColor:'Cor personalizada',applyCustom:'Aplicar cor',presets:'Cores premium',pdf:'Estilo PDF',doctorCard:'Cartão médico',signature:'Assinatura',tools:'Ferramentas e preferências da clínica.',noBA:'Marque uma foto como Antes e outra como Depois no menu de 3 pontos.',noPhotos:'Nenhuma foto nesta seção.',baHint:'As fotos Antes/Depois são escolhidas no menu de 3 pontos. Mova a barra para uma transição suave.',addPayment:'+ Adicionar pagamento',installments:'Parcelas',receipt:'Recibo',delete:'Excluir',patientTimeline:'Histórico do paciente',visit:'Visita'},
    tr:{native:'Türkçe',dir:'ltr',language:'Dil',languageHelp:'Uygulama arayüz dilini seçin.',menu:'Menü',dashboard:'Panel',patients:'Hastalar',addPatient:'Hasta ekle',scanQR:'QR tara',settings:'Ayarlar',profile:'Profil',manageUsers:'Kullanıcılar',logout:'Çıkış',search:'Ad, telefon, ID veya teşhis ara...',totalPatients:'Toplam hasta',todaysAppts:'Bugünkü randevular',unpaidBalance:'Ödenmemiş bakiye',totalVisits:'Toplam ziyaret',totalRevenue:'Toplam gelir',paidToday:'Bugün ödenen',clinicOverview:'Klinik özeti',appointmentCalendar:'Takvim',today:'Bugün',upcoming:'Yaklaşan',newPatient:'+ Yeni hasta',backup:'Yedek',restore:'Geri yükle',open:'Aç',withoutTreatmentPlan:'tedavi plansız',overdue:'gecikmiş',unpaid:'ödenmemiş',followUpWatch:'Takip',treatmentStats:'Tedavi istatistikleri',unpaidPriority:'Ödenmemiş öncelik',remaining:'Kalan',cases:'vaka',photos:'Fotoğraflar / Röntgen',clinical:'Klinik',xray:'Röntgen',beforeAfter:'Önce / Sonra',general:'Genel',before:'Önce',after:'Sonra',photoOptions:'Foto seçenekleri',markAs:'Olarak işaretle',viewPhoto:'Fotoğrafı aç',theme:'Renk',themeHelp:'Premium veya özel renk seçin.',customColor:'Özel renk',applyCustom:'Uygula',presets:'Premium renkler',pdf:'PDF stili',doctorCard:'Doktor kartı',signature:'İmza',tools:'Klinik araçları ve ayarları.',noBA:'3 nokta menüsünden bir fotoğrafı Önce, birini Sonra olarak işaretleyin.',noPhotos:'Bu bölümde fotoğraf yok.',baHint:'Önce/Sonra fotoğrafları 3 nokta menüsünden seçilir. Yumuşak geçiş için çubuğu hareket ettirin.',addPayment:'+ Ödeme ekle',installments:'Taksitler',receipt:'Makbuz',delete:'Sil',patientTimeline:'Hasta zaman çizelgesi',visit:'Ziyaret'},
    ru:{native:'Русский',dir:'ltr',language:'Язык',languageHelp:'Выберите язык интерфейса.',menu:'Меню',dashboard:'Панель',patients:'Пациенты',addPatient:'Добавить пациента',scanQR:'QR скан',settings:'Настройки',profile:'Профиль',manageUsers:'Пользователи',logout:'Выйти',search:'Поиск имени, телефона, ID или диагноза...',totalPatients:'Всего пациентов',todaysAppts:'Приёмы сегодня',unpaidBalance:'Неоплачено',totalVisits:'Всего визитов',totalRevenue:'Общий доход',paidToday:'Оплачено сегодня',clinicOverview:'Обзор клиники',appointmentCalendar:'Календарь',today:'Сегодня',upcoming:'Предстоящие',newPatient:'+ Новый пациент',backup:'Резерв',restore:'Восстановить',open:'Открыть',withoutTreatmentPlan:'без плана лечения',overdue:'просрочено',unpaid:'не оплачено',followUpWatch:'Контроль',treatmentStats:'Статистика лечения',unpaidPriority:'Неоплаченные',remaining:'Осталось',cases:'случаи',photos:'Фото / Рентген',clinical:'Клинические',xray:'Рентген',beforeAfter:'До / После',general:'Общие',before:'До',after:'После',photoOptions:'Параметры фото',markAs:'Отметить как',viewPhoto:'Открыть фото',theme:'Цвет',themeHelp:'Выберите премиум или свой цвет.',customColor:'Свой цвет',applyCustom:'Применить',presets:'Премиум цвета',pdf:'Стиль PDF',doctorCard:'Карта врача',signature:'Подпись',tools:'Инструменты и настройки клиники.',noBA:'Отметьте одно фото как До, а другое как После в меню с 3 точками.',noPhotos:'В этом разделе нет фото.',baHint:'Фото До/После выбираются из меню с 3 точками. Двигайте ползунок для мягкого перехода.',addPayment:'+ Добавить оплату',installments:'Рассрочка',receipt:'Квитанция',delete:'Удалить',patientTimeline:'История пациента',visit:'Визит'},
    zh:{native:'中文',dir:'ltr',language:'语言',languageHelp:'选择应用界面语言。',menu:'菜单',dashboard:'仪表板',patients:'患者',addPatient:'添加患者',scanQR:'扫描 QR',settings:'设置',profile:'资料',manageUsers:'用户',logout:'退出',search:'搜索姓名、电话、ID 或诊断...',totalPatients:'患者总数',todaysAppts:'今日预约',unpaidBalance:'未付余额',totalVisits:'总访问',totalRevenue:'总收入',paidToday:'今日已付',clinicOverview:'诊所概览',appointmentCalendar:'预约日历',today:'今天',upcoming:'即将到来',newPatient:'+ 新患者',backup:'备份',restore:'恢复',open:'打开',withoutTreatmentPlan:'无治疗计划',overdue:'逾期',unpaid:'未付',followUpWatch:'随访监控',treatmentStats:'治疗统计',unpaidPriority:'未付款优先',remaining:'剩余',cases:'病例',photos:'照片 / X光',clinical:'临床',xray:'X光',beforeAfter:'前 / 后',general:'普通',before:'前',after:'后',photoOptions:'照片选项',markAs:'标记为',viewPhoto:'查看照片',theme:'主题色',themeHelp:'选择高级预设或自定义颜色。',customColor:'自定义颜色',applyCustom:'应用颜色',presets:'高级预设',pdf:'PDF 样式',doctorCard:'医生卡',signature:'签名',tools:'诊所工具和偏好设置。',noBA:'请从三点菜单标记一张前照和一张后照。',noPhotos:'此部分没有照片。',baHint:'前后照片来自三点菜单。移动滑杆实现柔和过渡。',addPayment:'+ 添加付款',installments:'分期',receipt:'收据',delete:'删除',patientTimeline:'患者时间线',visit:'访问'},
    hi:{native:'हिन्दी',dir:'ltr',language:'भाषा',languageHelp:'ऐप इंटरफ़ेस की भाषा चुनें।',menu:'मेनू',dashboard:'डैशबोर्ड',patients:'मरीज़',addPatient:'मरीज़ जोड़ें',scanQR:'QR स्कैन',settings:'सेटिंग्स',profile:'प्रोफ़ाइल',manageUsers:'यूज़र',logout:'लॉग आउट',search:'नाम, फोन, ID या निदान खोजें...',totalPatients:'कुल मरीज़',todaysAppts:'आज की अपॉइंटमेंट',unpaidBalance:'बकाया राशि',totalVisits:'कुल विज़िट',totalRevenue:'कुल आय',paidToday:'आज भुगतान',clinicOverview:'क्लिनिक अवलोकन',appointmentCalendar:'अपॉइंटमेंट कैलेंडर',today:'आज',upcoming:'आगामी',newPatient:'+ नया मरीज़',backup:'बैकअप',restore:'रीस्टोर',open:'खोलें',withoutTreatmentPlan:'बिना उपचार योजना',overdue:'देरी',unpaid:'अवैतनिक',followUpWatch:'फॉलो-अप',treatmentStats:'उपचार आँकड़े',unpaidPriority:'बकाया प्राथमिकता',remaining:'शेष',cases:'केस',photos:'फोटो / एक्स-रे',clinical:'क्लिनिकल',xray:'एक्स-रे',beforeAfter:'पहले / बाद',general:'सामान्य',before:'पहले',after:'बाद',photoOptions:'फोटो विकल्प',markAs:'चिह्नित करें',viewPhoto:'फोटो देखें',theme:'रंग',themeHelp:'प्रीमियम रंग या कस्टम रंग चुनें।',customColor:'कस्टम रंग',applyCustom:'रंग लागू करें',presets:'प्रीमियम रंग',pdf:'PDF शैली',doctorCard:'डॉक्टर कार्ड',signature:'हस्ताक्षर',tools:'क्लिनिक टूल और सेटिंग्स।',noBA:'3-dot मेनू से एक फोटो Before और एक After चिह्नित करें।',noPhotos:'इस सेक्शन में कोई फोटो नहीं है।',baHint:'Before/After फोटो 3-dot मेनू से चुने जाते हैं। सॉफ्ट ट्रांज़िशन के लिए बार चलाएं।',addPayment:'+ भुगतान जोड़ें',installments:'किश्तें',receipt:'रसीद',delete:'हटाएं',patientTimeline:'मरीज़ टाइमलाइन',visit:'विज़िट'},
    ur:{native:'اردو',dir:'rtl',language:'زبان',languageHelp:'ایپ انٹرفیس کی زبان منتخب کریں۔',menu:'مینو',dashboard:'ڈیش بورڈ',patients:'مریض',addPatient:'مریض شامل کریں',scanQR:'QR اسکین',settings:'ترتیبات',profile:'پروفائل',manageUsers:'صارفین',logout:'لاگ آؤٹ',search:'نام، فون، ID یا تشخیص تلاش کریں...',totalPatients:'کل مریض',todaysAppts:'آج کی اپائنٹمنٹس',unpaidBalance:'بقایہ رقم',totalVisits:'کل وزٹس',totalRevenue:'کل آمدنی',paidToday:'آج ادا شدہ',clinicOverview:'کلینک کا جائزہ',appointmentCalendar:'اپائنٹمنٹ کیلنڈر',today:'آج',upcoming:'آنے والی',newPatient:'+ نیا مریض',backup:'بیک اپ',restore:'بحال',open:'کھولیں',withoutTreatmentPlan:'بغیر علاج پلان',overdue:'تاخیر',unpaid:'بقایہ',followUpWatch:'فالو اپ',treatmentStats:'علاج کے اعداد و شمار',unpaidPriority:'بقایہ ترجیح',remaining:'باقی',cases:'کیسز',photos:'تصاویر / ایکس رے',clinical:'کلینیکل',xray:'ایکس رے',beforeAfter:'پہلے / بعد',general:'عام',before:'پہلے',after:'بعد',photoOptions:'تصویر کے اختیارات',markAs:'نشان لگائیں',viewPhoto:'تصویر دیکھیں',theme:'رنگ',themeHelp:'پریمیم یا کسٹم رنگ منتخب کریں۔',customColor:'کسٹم رنگ',applyCustom:'رنگ لگائیں',presets:'پریمیم رنگ',pdf:'PDF انداز',doctorCard:'ڈاکٹر کارڈ',signature:'دستخط',tools:'کلینک ٹولز اور سیٹنگز۔',noBA:'تین نقطوں والے مینو سے ایک تصویر پہلے اور ایک بعد کے طور پر نشان لگائیں۔',noPhotos:'اس حصے میں کوئی تصویر نہیں۔',baHint:'پہلے/بعد کی تصاویر تین نقطوں والے مینو سے منتخب ہوتی ہیں۔ نرم منتقلی کے لیے بار حرکت دیں۔',addPayment:'+ ادائیگی شامل کریں',installments:'اقساط',receipt:'رسید',delete:'حذف',patientTimeline:'مریض کا ریکارڈ',visit:'وزٹ'},
    fa:{native:'فارسی',dir:'rtl',language:'زبان',languageHelp:'زبان رابط برنامه را انتخاب کنید.',menu:'منو',dashboard:'داشبورد',patients:'بیماران',addPatient:'افزودن بیمار',scanQR:'اسکن QR',settings:'تنظیمات',profile:'پروفایل',manageUsers:'کاربران',logout:'خروج',search:'جستجو بر اساس نام، تلفن، ID یا تشخیص...',totalPatients:'کل بیماران',todaysAppts:'نوبت‌های امروز',unpaidBalance:'مانده پرداخت نشده',totalVisits:'کل ویزیت‌ها',totalRevenue:'درآمد کل',paidToday:'پرداخت امروز',clinicOverview:'نمای کلی کلینیک',appointmentCalendar:'تقویم نوبت‌ها',today:'امروز',upcoming:'آینده',newPatient:'+ بیمار جدید',backup:'پشتیبان',restore:'بازیابی',open:'باز کردن',withoutTreatmentPlan:'بدون طرح درمان',overdue:'عقب‌افتاده',unpaid:'پرداخت نشده',followUpWatch:'پیگیری',treatmentStats:'آمار درمان',unpaidPriority:'اولویت بدهی',remaining:'مانده',cases:'مورد',photos:'عکس‌ها / رادیوگرافی',clinical:'کلینیکی',xray:'رادیوگرافی',beforeAfter:'قبل / بعد',general:'عمومی',before:'قبل',after:'بعد',photoOptions:'گزینه‌های عکس',markAs:'علامت‌گذاری به عنوان',viewPhoto:'نمایش عکس',theme:'رنگ',themeHelp:'یک رنگ آماده یا رنگ دلخواه انتخاب کنید.',customColor:'رنگ دلخواه',applyCustom:'اعمال رنگ',presets:'رنگ‌های ویژه',pdf:'سبک PDF',doctorCard:'کارت پزشک',signature:'امضا',tools:'ابزارها و تنظیمات کلینیک.',noBA:'از منوی سه نقطه یک عکس قبل و یک عکس بعد تعیین کنید.',noPhotos:'عکسی در این بخش نیست.',baHint:'عکس‌های قبل/بعد از منوی سه نقطه انتخاب می‌شوند. برای انتقال نرم نوار را حرکت دهید.',addPayment:'+ افزودن پرداخت',installments:'اقساط',receipt:'رسید',delete:'حذف',patientTimeline:'سوابق بیمار',visit:'ویزیت'}
  };
  const IOS_LANGS = [['af','Afrikaans'],['am','አማርኛ'],['az','Azərbaycanca'],['bg','Български'],['bn','বাংলা'],['bs','Bosanski'],['ca','Català'],['cs','Čeština'],['cy','Cymraeg'],['da','Dansk'],['el','Ελληνικά'],['et','Eesti'],['eu','Euskara'],['fi','Suomi'],['fil','Filipino'],['ga','Gaeilge'],['gl','Galego'],['gu','ગુજરાતી'],['he','עברית'],['hr','Hrvatski'],['hu','Magyar'],['id','Bahasa Indonesia'],['is','Íslenska'],['ja','日本語'],['kn','ಕನ್ನಡ'],['kk','Қазақша'],['km','ភាសាខ្មែរ'],['ko','한국어'],['lo','ລາວ'],['lt','Lietuvių'],['lv','Latviešu'],['mk','Македонски'],['ml','മലയാളം'],['mn','Монгол'],['mr','मराठी'],['ms','Bahasa Melayu'],['my','မြန်မာ'],['nb','Norsk Bokmål'],['ne','नेपाली'],['nl','Nederlands'],['pa','ਪੰਜਾਬੀ'],['pl','Polski'],['ro','Română'],['sk','Slovenčina'],['sl','Slovenščina'],['sq','Shqip'],['sr','Српски'],['sv','Svenska'],['sw','Kiswahili'],['ta','தமிழ்'],['te','తెలుగు'],['th','ไทย'],['uk','Українська'],['vi','Tiếng Việt'],['zu','Zulu']];
  IOS_LANGS.forEach(([code,native])=>{ if(!PACKS[code]) PACKS[code] = Object.assign({}, PACKS.en, {native, dir:RTL.has(code)?'rtl':'ltr'}); });
  function currentLang(){ return localStorage.getItem('clinicLanguage') || 'en'; }
  function L(key){ const p = PACKS[currentLang()] || PACKS.en; return p[key] || PACKS.en[key] || key; }
  try { window.__LANG_PACKS__ = PACKS; window.getLang = getLang = currentLang; window.t = t = L; } catch(e) { window.getLang = currentLang; window.t = L; }

  const textMap = {
    'Dashboard':'dashboard','Patients':'patients','Add Patient':'addPatient','Scan QR':'scanQR','Settings':'settings','Profile':'profile','Manage Users':'manageUsers','Logout':'logout','Menu':'menu','Search by name, phone, ID, or diagnosis...':'search','Search name, phone, ID, diagnosis...':'search','Total Patients':'totalPatients',"Today's Appts":'todaysAppts','Unpaid Balance':'unpaidBalance','Total Visits':'totalVisits','Total Revenue':'totalRevenue','Paid Today':'paidToday','Clinic Overview':'clinicOverview','Appointment Calendar':'appointmentCalendar','Today':'today','Upcoming':'upcoming','+ New Patient':'newPatient','Backup':'backup','Restore':'restore','Open':'open','without treatment plan':'withoutTreatmentPlan','overdue':'overdue','unpaid':'unpaid','Follow-up Watch':'followUpWatch','Treatment Stats':'treatmentStats','Unpaid Priority':'unpaidPriority','Remaining':'remaining','cases':'cases','Photos / X-rays':'photos','Clinical':'clinical','X-ray':'xray','X-rays':'xray','Before / After':'beforeAfter','General':'general','Before':'before','After':'after','Photo options':'photoOptions','Mark as':'markAs','View photo':'viewPhoto','Theme color':'theme','PDF style':'pdf','Doctor card':'doctorCard','Draw signature':'signature','Custom color':'customColor','Apply custom color':'applyCustom','Premium presets':'presets','+ Add Payment':'addPayment','Add Payment +':'addPayment','Installments':'installments','Receipt':'receipt','Delete':'delete','Patient Timeline':'patientTimeline','VISIT':'visit','Visit':'visit','Language':'language'
  };
  const allLocalized = {};
  Object.values(PACKS).forEach(pack => Object.keys(pack).forEach(k => { if(k==='native' || k==='dir') return; const v = pack[k]; if(typeof v === 'string') allLocalized[v] = k; }));
  function keyForText(txt){ return textMap[txt] || allLocalized[txt]; }
  function applyText(root){
    const code = currentLang(); const pack = PACKS[code] || PACKS.en;
    document.documentElement.lang = code; document.documentElement.dir = pack.dir || 'ltr'; document.body.dir = pack.dir || 'ltr'; document.body.dataset.lang = code;
    document.querySelectorAll('[data-page="dashboard"]').forEach(el=>el.textContent=L('dashboard'));
    document.querySelectorAll('[data-page="patients"]').forEach(el=>el.textContent=L('patients'));
    document.querySelectorAll('[data-page="form"]').forEach(el=>el.textContent=L('addPatient'));
    document.querySelectorAll('[data-page="scan"]').forEach(el=>el.textContent=L('scanQR'));
    const menuBtn = document.getElementById('menuBtn'); if(menuBtn) menuBtn.textContent = L('menu');
    const search = document.getElementById('search'); if(search) search.placeholder = L('search');
    document.querySelectorAll('input[placeholder], textarea[placeholder]').forEach(el=>{ const k = keyForText(el.getAttribute('placeholder')); if(k) el.setAttribute('placeholder', L(k)); });
    const walker = document.createTreeWalker(root || document.body, NodeFilter.SHOW_TEXT, {acceptNode(n){ if(!n.nodeValue || !n.nodeValue.trim()) return NodeFilter.FILTER_REJECT; const p=n.parentElement; if(!p || ['SCRIPT','STYLE','TEXTAREA','INPUT','OPTION'].includes(p.tagName)) return NodeFilter.FILTER_REJECT; if(p.closest('#languageCleanOverlay, .no-translate, [translate="no"], [data-native-code], .clean-language-item')) return NodeFilter.FILTER_REJECT; return NodeFilter.FILTER_ACCEPT; }});
    const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach(n=>{ const raw=n.nodeValue.trim(); const k=keyForText(raw); if(k) n.nodeValue = n.nodeValue.replace(raw, L(k)); });
  }
  window.applyLanguage = applyLanguage = function(){ applyText(document.body); };
  window.setUILanguage = setUILanguage = function(code){
    localStorage.setItem('clinicLanguage', PACKS[code] ? code : 'en');
    document.getElementById('languageCleanOverlay')?.remove();
    try { if(typeof renderDashboard==='function') renderDashboard(); } catch(e) {}
    try { if(typeof renderPatients==='function') renderPatients(); } catch(e) {}
    try { if(document.getElementById('detail')?.classList.contains('active') && window.__lastOpenedPatientId && typeof openPatient==='function') openPatient(window.__lastOpenedPatientId); } catch(e) {}
    setTimeout(()=>applyText(document.body),0);
    setTimeout(()=>applyText(document.body),120);
  };
  window.openLanguagePicker = function(){
    document.getElementById('languageCleanOverlay')?.remove();
    const current = currentLang();
    const codes = Object.keys(PACKS).sort((a,b)=>(PACKS[a].native||a).localeCompare(PACKS[b].native||b));
    const overlay = document.createElement('div'); overlay.id='languageCleanOverlay'; overlay.className='clean-modal-overlay no-translate'; overlay.setAttribute('translate','no');
    overlay.innerHTML = `<div class="clean-modal clean-language-modal final-language-modal no-translate" role="dialog" aria-modal="true" dir="ltr" translate="no"><div class="clean-modal-head"><div><h2>${safeText(L('language'))}</h2><p>${safeText(L('languageHelp'))}</p></div><button type="button" onclick="document.getElementById('languageCleanOverlay')?.remove()">×</button></div><div class="final-language-search"><input id="languageSearchInput" placeholder="Search language..." oninput="filterLanguagesFinal(this.value)"></div><div class="clean-language-grid final-language-grid">${codes.map(code=>`<button type="button" translate="no" data-native-code="${code}" data-language-item="${safeText(code+' '+PACKS[code].native)}" class="clean-language-item no-translate ${current===code?'active':''}" dir="${PACKS[code].dir}" onclick="setUILanguage('${code}')"><strong translate="no">${safeText(PACKS[code].native)}</strong><span translate="no">${safeText(code.toUpperCase())}</span></button>`).join('')}</div></div>`;
    overlay.addEventListener('click', e=>{ if(e.target===overlay) overlay.remove(); });
    document.body.appendChild(overlay);
    setTimeout(()=>document.getElementById('languageSearchInput')?.focus(),80);
  };
  window.filterLanguagesFinal = function(q){ q=String(q||'').toLowerCase(); document.querySelectorAll('[data-language-item]').forEach(btn=>{ btn.style.display = btn.dataset.languageItem.toLowerCase().includes(q) ? '' : 'none'; }); };
  try {
    const oldOpenPatient = openPatient;
    window.openPatient = openPatient = function(id){ window.__lastOpenedPatientId = id; const out = oldOpenPatient.apply(this, arguments); setTimeout(()=>applyText(document.body),0); setTimeout(()=>applyText(document.body),150); return out; };
  } catch(e) {}
  ['renderDashboard','renderPatients','showPage'].forEach(name=>{
    try { const old = window[name] || eval(name); if(typeof old !== 'function' || old.__langWrapped) return; const wrapped=function(){ const out=old.apply(this, arguments); setTimeout(()=>applyText(document.body),0); setTimeout(()=>applyText(document.body),120); return out; }; wrapped.__langWrapped=true; window[name]=wrapped; eval(name+' = wrapped'); } catch(e) {}
  });
  let pending=false; const mo = new MutationObserver(()=>{ if(pending) return; pending=true; setTimeout(()=>{ pending=false; applyText(document.body); },60); });
  function start(){ applyText(document.body); try { mo.observe(document.body,{childList:true,subtree:true}); } catch(e) {} }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded', start, {once:true}); else start();
})();
